### ISSUE TITLE
--json and -tr

### ISSUE THREAD

**Issue by ethernetweb** [vergoh/vnstat#56] opened 2017-04-01 04:49 UTC
Greetings,

I have a feature request - 
It would be very helpful to my platform and usage needs if it were possible to get the -tr argument output in JSON format.

Thank you for work on this great product.

**Comment by vergoh** [comment] 2017-04-05 19:58
For only -tr, that shouldn't be hard too implement. Most likely the JSON output would need to contain a little bit more information (begin and end dates, duration etc.) than the current textual output in order to support more diverse uses.

This appears to be at least partially a duplicate of issue #25.

**Comment by ethernetweb** [comment] 2017-04-05 20:21
Hah, my fault - I overlooked that somehow. I did look at the other issues but that one appears to have escaped me somehow. Thank you again and my apologies for the dupe.

As I've noticed the -tr requires a minimum of a 2 second duration to check (that's what my config option is now). Currently, I'm just using regexp to parse the output as a string. Being able to specify the duration with a command line argument would be slick as well.

**Comment by vergoh** [comment] 2017-04-06 20:29
You can already provide -tr with a numeric parameter that will then define the duration in seconds. At least the man page has that documentation. :-)

The 2 second minimum is there to a least average the result a little bit. I recall that the data source vnStat uses updates only about once every second.

**Closed** 2018-02-14 16:32 UTC
Labels: duplicate, feature request
